name: Docker image build

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        TAG="$(date +%s)"
        docker build -t dummy:test-$TAG .

    - name: Run image
      run: docker run dummy:test-$TAG