name: Docker image build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.new_tag.outputs.date }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create tag
        id: new_tag
        run: echo "date=test-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: docker build -t dummy:test-${{ steps.new_tag.outputs.date }} .

      - name: Run image
        run: docker run dummy:test-${{ steps.new_tag.outputs.date }}