name: github_contexts
run-name: 'github contexts'

on:
  pull_request_target:
    branches: [main]
    types: [closed]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: curl from contexts
        run: |
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          curl https://raw.githubusercontent.com/fherreazcue/dummy/${{ github.base_ref }}/curltest.txt --output base_curl.txt
          cat base_curl.txt
          curl https://raw.githubusercontent.com/fherreazcue/dummy/${{ github.head_ref }}/curltest.txt --output head_curl.txt
          cat head_curl.txt
          curl https://raw.githubusercontent.com/fherreazcue/dummy/${{ github.ref }}/curltest.txt --output ref_curl.txt
          cat ref_curl.txt
          curl https://raw.githubusercontent.com/fherreazcue/dummy/${{ github.ref_name }}/curltest.txt --output ref_name_curl.txt
          cat ref_name_curl.txt
