name: ansible-install
run-name: ${{ github.actor }} is testing Ansible install
on:
  push:
  #workflow_dispatch:
jobs:
  install-seek-from-ansible:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-20.04,ubuntu-22.04,ubuntu-latest]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup ansible
      #   run: npm ansible

      - name: Configure ansible for local install
        run: |
          sed -i '/^vault_password_file/d' ansible.cfg
          sed -i '/^[ssh_connection]/d' ansible.cfg
          sed -i '/^pipelining = true/d' ansible.cfg
          sed -i 's/^- hosts: [servers]/- hosts: localhost/' Deploy-dummy.yml
          sed -i '/- hosts: localhost/a   connection: local' Deploy-dummy.yml

      - name: Check sed worked
        run: |
          cat ansible.cfg
          cat Deploy-dummy.yml

      - name: Install dummy through ansible
        run: ansible-playbook Deploy-dummy.yml