name: ansible-install
run-name: ${{ github.actor }} is testing Ansible install
on:
  push:
  #workflow_dispatch:
jobs:
  install-seek-from-ansible:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-20.04,ubuntu-22.04,ubuntu-latest]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup ansible
      #   run: npm ansible

      - name: Configure ansible for local install
        run: |
          sed -i '/vault_password_file/d' ansible.cfg
          sed -i '/ssh_connection/d' ansible.cfg
          sed -i '/pipelining/d' ansible.cfg
          sed -i 's/\- hosts\: \[servers\]/\- hosts\: localhost/g' Deploy-dummy.yml
          sed -i '/\- hosts\: localhost/a \ \ connection\: local' Deploy-dummy.yml

      - name: Check sed worked in cfg
        run: |
          cat ansible.cfg

      - name: Check sed worked in deploy
        run: |
          cat Deploy-dummy.yml

      - name: Configure variables
        run: |
          sed -i 's/user_var\: francisco/user_var\: runner/' group_vars/vars.yml
          sed -i 's/git_dest\: \/home\/francisco/git_dest\: \/home\/runner\/work/' group_vars/vars.yml
      
      - name: Check sed worked in vars
        run: |
          cat group_vars/vars.yml

      - name: Install dummy through ansible
        run: ansible-playbook Deploy-dummy.yml

      - name: Check tree
        run: |
          tree /home/runner/work