name: learn-github-actions
run-name: ${{ github.actor }} is testing an action
on:
  workflow_dispatch:
    inputs:
      linux:
        description: "Linux?"
        required: true
        type: boolean
        default: true
      macos:
        description: "macOS?"
        required: true
        type: boolean
        default: true
      windows:
        description: "Windows?"
        required: true
        type: boolean
        default: true
      A:
        description: "A?"
        required: true
        type: boolean
        default: true
      B:
        description: "B?"
        required: true
        type: boolean
        default: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            do_something: ${{github.event.inputs.linux}}
          - os: windows-latest
            do_something: ${{github.event.inputs.windows}}
          - os: macos-latest
            do_something: ${{github.event.inputs.macos}}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Echo something
        run : |
          echo "Hello from ${{ matrix.os }}"
          echo "do_something? ${{ matrix.do_something }}"
